import type { CatalogKpi, IndustryId } from "./types";

const C = (
  p: CatalogKpi,
): CatalogKpi => p;

export const CATALOG: CatalogKpi[] = [
  C({
    key: "retail.conversion",
    category: "retail",
    name: "Store conversion rate",
    nameAr: "معدل التحويل في المتجر",
    definition: "Percentage of tracked visitors who complete a paid transaction in the same visit.",
    purpose: "Tell store leadership whether traffic is being converted, not merely counted.",
    unit: "%",
    direction: "higher",
    frequency: "weekly",
    formula: "(Transactions / Tracked visitors) × 100",
    numerator: "Transactions",
    denominator: "Tracked visitors",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quantity",
    parmenterType: "KPI",
    ipoo: "process",
    gamingRisk: "Staff may avoid greeting browsers who look unlikely to buy, or under-count visitors.",
    gamingSeverity: "medium",
    guardrail: "Pair with average transaction value and mystery-shop / CSAT so staff do not filter traffic.",
    dataSource: "POS + door / analytics counter",
  }),
  C({
    key: "retail.atv",
    category: "retail",
    name: "Average transaction value",
    nameAr: "متوسط قيمة العملية",
    definition: "Net sales divided by number of transactions in the period, after returns.",
    purpose: "See whether commercial mix and attach rates are improving independently of traffic.",
    unit: "currency",
    direction: "higher",
    frequency: "weekly",
    formula: "Net sales / Transaction count",
    numerator: "Net sales",
    denominator: "Transaction count",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quantity",
    parmenterType: "RI",
    ipoo: "output",
    gamingRisk: "Pushing unwanted add-ons or delaying returns to inflate ATV.",
    gamingSeverity: "medium",
    guardrail: "Return rate and items-per-transaction quality checks.",
    dataSource: "POS",
  }),
  C({
    key: "retail.margin",
    category: "retail",
    name: "Gross margin %",
    nameAr: "هامش الربح الإجمالي %",
    definition: "Gross profit as a percentage of net sales after discounts and shrink adjustments.",
    purpose: "Prevent revenue-only behaviour. This is the primary commercial guardrail.",
    unit: "%",
    direction: "higher",
    frequency: "weekly",
    formula: "((Net sales − COGS) / Net sales) × 100",
    numerator: "Gross profit",
    denominator: "Net sales",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KRI",
    ipoo: "outcome",
    gamingRisk: "Misclassifying discounts or delaying cost recognition.",
    gamingSeverity: "medium",
    guardrail: "Finance-owned COGS definition; no store-level override.",
    dataSource: "Finance / POS",
  }),
  C({
    key: "retail.repeat",
    category: "retail",
    name: "Repeat purchase rate (90 days)",
    nameAr: "معدل الشراء المتكرر (90 يوماً)",
    definition: "Share of identified customers who make a second paid purchase within 90 days.",
    purpose: "Detect whether growth is from genuine demand or one-off discount hunting.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "Repeat identified customers / Identified customers in cohort",
    numerator: "Repeat customers",
    denominator: "Cohort customers",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Splitting baskets or creating dummy customer records.",
    gamingSeverity: "low",
    guardrail: "Use identified customers only; exclude staff purchases.",
    dataSource: "CRM / loyalty",
  }),
  C({
    key: "retail.shrink",
    category: "retail",
    name: "Shrink %",
    nameAr: "نسبة الفاقد",
    definition: "Unexplained inventory loss as a percentage of sales.",
    purpose: "Protect profit and integrity. A productivity KPI without shrink is incomplete.",
    unit: "%",
    direction: "lower",
    frequency: "monthly",
    formula: "(Book inventory − Counted inventory) / Sales",
    numerator: "Unexplained loss",
    denominator: "Sales",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quality",
    parmenterType: "KRI",
    ipoo: "outcome",
    gamingRisk: "Delaying counts or writing losses into other accounts.",
    gamingSeverity: "medium",
    guardrail: "Independent cycle counts; no store self-attestation as sole source.",
    dataSource: "Inventory system",
  }),
  C({
    key: "sales.winrate",
    category: "sales",
    name: "Qualified win rate",
    nameAr: "معدل ربح الفرص المؤهلة",
    definition: "Won opportunities divided by qualified opportunities that reached a decision in the period.",
    purpose: "Measure sales effectiveness, not activity volume.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "Won / (Won + Lost qualified)",
    numerator: "Won deals",
    denominator: "Decided qualified deals",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Sandbagging qualification so only easy deals enter the denominator.",
    gamingSeverity: "high",
    guardrail: "Stable qualification definition; audit of disqualified deals.",
    dataSource: "CRM",
  }),
  C({
    key: "sales.cycletime",
    category: "sales",
    name: "Median sales cycle (qualified to close)",
    nameAr: "وسيط دورة المبيعات",
    definition: "Median days from qualification to close for decided deals.",
    purpose: "Expose pipeline friction without rewarding rushed, low-quality closes.",
    unit: "days",
    direction: "lower",
    frequency: "monthly",
    formula: "Median(close date − qualification date)",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "PI",
    ipoo: "process",
    gamingRisk: "Delaying qualification dates or closing prematurely.",
    gamingSeverity: "medium",
    guardrail: "Pair with win rate, gross margin and refund / churn in first 90 days.",
    dataSource: "CRM",
  }),
  C({
    key: "sales.pipeline",
    category: "sales",
    name: "Qualified pipeline coverage",
    nameAr: "تغطية خط الأنابيب المؤهل",
    definition: "Weighted qualified pipeline divided by remaining period target.",
    purpose: "A leading signal of whether the target is even mathematically reachable.",
    unit: "ratio",
    direction: "higher",
    frequency: "weekly",
    formula: "Weighted qualified pipeline / Remaining target",
    numerator: "Weighted pipeline",
    denominator: "Remaining target",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quantity",
    parmenterType: "PI",
    ipoo: "input",
    gamingRisk: "Inflating probability or recycling stale deals.",
    gamingSeverity: "high",
    guardrail: "Ageing rules; deals older than the median cycle are excluded or heavily discounted.",
    dataSource: "CRM",
  }),
  C({
    key: "sales.ndr",
    category: "sales",
    name: "Net revenue retention",
    nameAr: "صافي الاحتفاظ بالإيراد",
    definition: "Starting ARR plus expansion minus contraction and churn, divided by starting ARR.",
    purpose: "For recurring models, this is usually a better KPI than new logo count.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "(Start ARR + expansion − contraction − churn) / Start ARR × 100",
    numerator: "Ending ARR from starting cohort",
    denominator: "Starting ARR",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Reclassifying churn as pause, or booking expansion that will reverse.",
    gamingSeverity: "medium",
    guardrail: "Finance definition of ARR; no sales-ops override.",
    dataSource: "Billing / finance",
  }),
  C({
    key: "hr.regrettable",
    category: "hr",
    name: "Regrettable attrition %",
    nameAr: "نسبة التسرب المؤسف",
    definition: "Voluntary exits of employees the organisation wanted to retain, as a % of average headcount.",
    purpose: "Stop treating all turnover as equal. This is usually the real people risk.",
    unit: "%",
    direction: "lower",
    frequency: "monthly",
    formula: "Regrettable exits / Average headcount × 100",
    numerator: "Regrettable exits",
    denominator: "Average headcount",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Reclassifying regretted leavers as non-regrettable after the fact.",
    gamingSeverity: "high",
    guardrail: "Classification locked at exit interview with two-party sign-off.",
    dataSource: "HRIS",
  }),
  C({
    key: "hr.ttp",
    category: "hr",
    name: "Time to productivity (new hires)",
    nameAr: "الوقت حتى الإنتاجية",
    definition: "Median days until a new hire meets the role’s agreed productivity standard.",
    purpose: "Hiring volume without this measure hides onboarding failure.",
    unit: "days",
    direction: "lower",
    frequency: "monthly",
    formula: "Median days from start date to standard met",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Lowering the productivity standard so the number looks better.",
    gamingSeverity: "medium",
    guardrail: "Standard defined per role before hire; not editable by the hiring manager after start.",
    dataSource: "HRIS + manager attestation",
  }),
  C({
    key: "hr.offer",
    category: "hr",
    name: "Offer acceptance rate",
    nameAr: "معدل قبول العروض",
    definition: "Accepted offers divided by offers extended in the period.",
    purpose: "Diagnose employer-value problems before blaming the labour market.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "Accepted / Offers extended × 100",
    numerator: "Accepted offers",
    denominator: "Offers extended",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quantity",
    parmenterType: "PI",
    ipoo: "process",
    gamingRisk: "Only extending offers to candidates already coached to say yes.",
    gamingSeverity: "low",
    guardrail: "Track reasons for decline; do not shrink the funnel artificially.",
    dataSource: "ATS",
  }),
  C({
    key: "hr.engagement",
    category: "hr",
    name: "eNPS / engagement (response-weighted)",
    nameAr: "مؤشر تفاعل الموظفين",
    definition: "Employee net promoter or engagement index, reported only when response rate clears the threshold.",
    purpose: "A people outcome — but only if the sample is honest.",
    unit: "index",
    direction: "higher",
    frequency: "quarterly",
    formula: "% promoters − % detractors, if response rate ≥ threshold, else insufficient data",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KRI",
    ipoo: "outcome",
    gamingRisk: "Selective distribution, manager pressure, hiding low-response teams.",
    gamingSeverity: "high",
    guardrail: "Publish response rate beside the score. Below threshold = insufficient data, not a number.",
    dataSource: "Survey tool",
  }),
  C({
    key: "hr.ninety",
    category: "hr",
    name: "90-day new-hire retention",
    nameAr: "الاحتفاظ بالموظف خلال 90 يوماً",
    definition: "Percentage of new hires still employed and not in exit process at day 90.",
    purpose: "The fastest quality check on hiring and onboarding.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "New hires retained at 90 days / New hires who reached day 90",
    numerator: "Retained",
    denominator: "Cohort reaching day 90",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Delaying resignations or converting exits to contractor status.",
    gamingSeverity: "medium",
    guardrail: "Include all exits, including ‘mutual’.",
    dataSource: "HRIS",
  }),
  C({
    key: "ops.otif",
    category: "operations",
    name: "On-time in-full (OTIF)",
    nameAr: "التسليم في الوقت وبالكامل",
    definition: "Orders delivered by the promised date with complete, correct lines.",
    purpose: "The core operational promise to the customer.",
    unit: "%",
    direction: "higher",
    frequency: "weekly",
    formula: "OTIF orders / Orders due × 100",
    numerator: "OTIF orders",
    denominator: "Orders due",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Moving promise dates, splitting orders, or excluding difficult customers.",
    gamingSeverity: "high",
    guardrail: "Promise date locked at order confirmation; no silent exclusions.",
    dataSource: "OMS / WMS",
  }),
  C({
    key: "ops.cycle",
    category: "operations",
    name: "Order cycle time",
    nameAr: "زمن دورة الطلب",
    definition: "Median hours from order release to shipment scan.",
    purpose: "A leading operational driver of OTIF.",
    unit: "hours",
    direction: "lower",
    frequency: "weekly",
    formula: "Median(shipment scan − release timestamp)",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "PI",
    ipoo: "process",
    gamingRisk: "Releasing orders late so the clock starts later.",
    gamingSeverity: "medium",
    guardrail: "Clock starts at customer-visible confirmation, not internal release.",
    dataSource: "OMS",
  }),
  C({
    key: "mfg.fpy",
    category: "manufacturing",
    name: "First-pass yield",
    nameAr: "العائد من أول مرة",
    definition: "Units that pass all quality checks first time, divided by units started.",
    purpose: "The primary quality KPI. Volume without FPY is a gaming invitation.",
    unit: "%",
    direction: "higher",
    frequency: "daily",
    formula: "First-pass good units / Units started × 100",
    numerator: "First-pass good units",
    denominator: "Units started",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Re-classifying rework as first-pass or skipping checks.",
    gamingSeverity: "high",
    guardrail: "Independent QA sampling; rework always in the denominator.",
    dataSource: "MES / QA",
  }),
  C({
    key: "mfg.oee",
    category: "manufacturing",
    name: "OEE (availability × performance × quality)",
    nameAr: "الفعالية الإجمالية للمعدات",
    definition: "Standard overall equipment effectiveness. Do not report a single blended number without the three factors.",
    purpose: "Capacity truth. Prevents hiding downtime inside a heroic output number.",
    unit: "%",
    direction: "higher",
    frequency: "daily",
    formula: "Availability × Performance × Quality",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "RI",
    ipoo: "output",
    gamingRisk: "Redefining planned downtime or lowering the ideal cycle time.",
    gamingSeverity: "high",
    guardrail: "Publish the three factors separately. Freeze ideal cycle time quarterly.",
    dataSource: "MES",
  }),
  C({
    key: "mfg.safety",
    category: "manufacturing",
    name: "Recordable incident rate",
    nameAr: "معدل الحوادث المسجّلة",
    definition: "OSHA-style recordable incidents per 200,000 hours worked.",
    purpose: "A non-negotiable guardrail on productivity KPIs.",
    unit: "rate",
    direction: "lower",
    frequency: "monthly",
    formula: "(Recordable incidents × 200000) / Hours worked",
    numerator: "Recordable incidents × 200000",
    denominator: "Hours worked",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KRI",
    ipoo: "outcome",
    gamingRisk: "Under-reporting, reclassifying incidents, discouraging reports.",
    gamingSeverity: "high",
    guardrail: "Near-miss reporting is encouraged and never used punitively. Safety is never a bonus suppressor that encourages silence.",
    dataSource: "EHS system",
  }),
  C({
    key: "mfg.scrap",
    category: "manufacturing",
    name: "Scrap & rework %",
    nameAr: "نسبة الهدر وإعادة التشغيل",
    definition: "Material and labour lost to scrap and rework as a percentage of output cost.",
    purpose: "The cost companion to first-pass yield.",
    unit: "%",
    direction: "lower",
    frequency: "weekly",
    formula: "(Scrap + rework cost) / Output cost × 100",
    numerator: "Scrap + rework cost",
    denominator: "Output cost",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quality",
    parmenterType: "PI",
    ipoo: "output",
    gamingRisk: "Capitalising rework or burying scrap in variance accounts.",
    gamingSeverity: "medium",
    guardrail: "Finance-owned cost definition.",
    dataSource: "MES + finance",
  }),
  C({
    key: "edu.mastery",
    category: "education",
    name: "Skill mastery rate (authenticated assessment)",
    nameAr: "معدل إتقان المهارة",
    definition: "Share of learners who meet the authenticated mastery standard on the intended assessment.",
    purpose: "Learner outcome — not attendance, not completion theatre.",
    unit: "%",
    direction: "higher",
    frequency: "per cohort",
    formula: "Learners meeting mastery / Learners assessed × 100",
    numerator: "Mastery achieved",
    denominator: "Learners assessed",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Easier tests, teaching to the item bank, excluding weak learners from assessment.",
    gamingSeverity: "high",
    guardrail: "Assessment blueprint frozen; report exclusion rate beside the score.",
    dataSource: "LMS / assessment",
  }),
  C({
    key: "edu.completion",
    category: "education",
    name: "Programme completion (eligible cohort)",
    nameAr: "إكمال البرنامج",
    definition: "Eligible learners who complete all required components, excluding administrative withdrawals.",
    purpose: "A supporting RI, never the sole learner KPI.",
    unit: "%",
    direction: "higher",
    frequency: "per cohort",
    formula: "Completers / Eligible starters × 100",
    numerator: "Completers",
    denominator: "Eligible starters",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quantity",
    parmenterType: "RI",
    ipoo: "output",
    gamingRisk: "Lowering requirements or pushing unready learners through.",
    gamingSeverity: "high",
    guardrail: "Must sit beside mastery / demonstration of skill.",
    dataSource: "SIS / LMS",
  }),
  C({
    key: "edu.apply",
    category: "training",
    name: "On-the-job application rate (30 days)",
    nameAr: "معدل تطبيق التعلّم في العمل",
    definition: "Share of trained staff whose manager confirms the skill was applied to live work within 30 days, against a checklist.",
    purpose: "Training exists to change work, not to fill seats.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "Confirmed applications / Completers × 100",
    numerator: "Confirmed applications",
    denominator: "Completers",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Rubber-stamp manager confirmations.",
    gamingSeverity: "medium",
    guardrail: "Checklist evidence required; sample audit of confirmations.",
    dataSource: "LMS + manager form",
  }),
  C({
    key: "cs.fcr",
    category: "customer_service",
    name: "First-contact resolution",
    nameAr: "الحل من أول تواصل",
    definition: "Contacts resolved without a follow-up on the same issue within 7 days.",
    purpose: "The effectiveness KPI. Volume of tickets closed is not a KPI.",
    unit: "%",
    direction: "higher",
    frequency: "weekly",
    formula: "Resolved first contact / Contacts × 100",
    numerator: "First-contact resolutions",
    denominator: "Contacts",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Closing tickets before the issue is solved, or coaching customers not to return.",
    gamingSeverity: "high",
    guardrail: "Reopen rate and CSAT as partner metrics.",
    dataSource: "Ticketing",
  }),
  C({
    key: "cs.csat",
    category: "customer_service",
    name: "Post-contact CSAT (response-weighted)",
    nameAr: "رضا ما بعد التواصل",
    definition: "Mean CSAT for contacts with a survey response, reported only above a response-rate threshold.",
    purpose: "Quality of the experience, if the sample is real.",
    unit: "score",
    direction: "higher",
    frequency: "weekly",
    formula: "Mean score if response rate ≥ threshold, else insufficient data",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "PI",
    ipoo: "outcome",
    gamingRisk: "Surveying only easy contacts.",
    gamingSeverity: "high",
    guardrail: "Random sample; publish response rate; no agent-triggered surveys.",
    dataSource: "Survey + ticketing",
  }),
  C({
    key: "fin.cash",
    category: "finance",
    name: "Cash conversion cycle",
    nameAr: "دورة تحويل النقد",
    definition: "DIO + DSO − DPO. Days to turn resource into cash.",
    purpose: "A real financial KPI, unlike ‘revenue’ alone.",
    unit: "days",
    direction: "lower",
    frequency: "monthly",
    formula: "DIO + DSO − DPO",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Delaying supplier payments unsustainably to look better.",
    gamingSeverity: "medium",
    guardrail: "Supplier OTIF and dispute rate as partner metrics.",
    dataSource: "ERP / finance",
  }),
  C({
    key: "fin.fcst",
    category: "finance",
    name: "Forecast accuracy (absolute)",
    nameAr: "دقة التنبؤ",
    definition: "1 − |Actual − Forecast| / Actual, for the locked forecast.",
    purpose: "The quality of planning. A target missed with a good forecast is different from a surprise.",
    unit: "%",
    direction: "higher",
    frequency: "monthly",
    formula: "1 − abs(actual − forecast) / actual",
    numerator: "1 − absolute error",
    denominator: "Actual",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "PI",
    ipoo: "process",
    gamingRisk: "Sandbagging forecasts or revising after the period starts.",
    gamingSeverity: "high",
    guardrail: "Forecast locked at period start; revisions versioned.",
    dataSource: "FP&A",
  }),
  C({
    key: "mkt.cac",
    category: "marketing",
    name: "CAC payback (months)",
    nameAr: "استرداد تكلفة الاكتساب",
    definition: "Customer acquisition cost divided by contribution margin per month.",
    purpose: "Stops celebrating cheap leads that never pay back.",
    unit: "months",
    direction: "lower",
    frequency: "monthly",
    formula: "CAC / Monthly contribution margin per new customer",
    numerator: "CAC",
    denominator: "Monthly contribution margin",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Pushing CAC into ‘brand’ so performance looks cheaper.",
    gamingSeverity: "high",
    guardrail: "Fully loaded CAC definition owned by finance.",
    dataSource: "Marketing + finance",
  }),
  C({
    key: "mkt.qual",
    category: "marketing",
    name: "Qualified pipeline from marketing",
    nameAr: "خط الأنابيب المؤهل من التسويق",
    definition: "Value of opportunities that pass sales qualification and originated from marketing.",
    purpose: "Marketing outcome that sales will actually own.",
    unit: "currency",
    direction: "higher",
    frequency: "monthly",
    formula: "Sum of qualified opportunity value with marketing origin",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quantity",
    parmenterType: "PI",
    ipoo: "output",
    gamingRisk: "Stuffing unqualified leads or arguing origin.",
    gamingSeverity: "medium",
    guardrail: "Shared qualification definition with sales.",
    dataSource: "CRM",
  }),
  C({
    key: "it.cfr",
    category: "it",
    name: "Change fail rate",
    nameAr: "معدل فشل التغيير",
    definition: "Changes that cause incident, rollback or hotfix, divided by changes shipped.",
    purpose: "DORA quality partner to throughput. Velocity without this is vanity.",
    unit: "%",
    direction: "lower",
    frequency: "weekly",
    formula: "Failed changes / Changes × 100",
    numerator: "Failed changes",
    denominator: "Changes",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Not classifying incidents as change-related, or batching to hide fails.",
    gamingSeverity: "medium",
    guardrail: "Incident-to-change linking required.",
    dataSource: "Deploy + incident systems",
  }),
  C({
    key: "it.lt",
    category: "it",
    name: "Lead time for change",
    nameAr: "زمن الانتظار للتغيير",
    definition: "Median time from first commit to production for the service.",
    purpose: "The flow KPI. Story points are not a KPI.",
    unit: "hours",
    direction: "lower",
    frequency: "weekly",
    formula: "Median(prod timestamp − first commit)",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "KPI",
    ipoo: "process",
    gamingRisk: "Squashing history or starting the clock at a later commit.",
    gamingSeverity: "medium",
    guardrail: "Clock starts at first commit on the default integration branch.",
    dataSource: "VCS + CD",
  }),
  C({
    key: "sc.fill",
    category: "supply_chain",
    name: "Supplier OTIF",
    nameAr: "التزام المورّد بالوقت والكمية",
    definition: "Inbound receipts on time and in full against the confirmed purchase order.",
    purpose: "Protects operations from hidden supplier failure.",
    unit: "%",
    direction: "higher",
    frequency: "weekly",
    formula: "OTIF receipts / Due receipts × 100",
    numerator: "OTIF receipts",
    denominator: "Due receipts",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "effectiveness",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Changing due dates after the fact.",
    gamingSeverity: "medium",
    guardrail: "Confirmed date frozen; buyer cannot silently move it.",
    dataSource: "ERP",
  }),
  C({
    key: "sc.turns",
    category: "supply_chain",
    name: "Inventory turns",
    nameAr: "دوران المخزون",
    definition: "COGS / Average inventory.",
    purpose: "Cash tied in stock. High turns with stockouts is a false win.",
    unit: "ratio",
    direction: "higher",
    frequency: "monthly",
    formula: "COGS / Average inventory",
    numerator: "COGS",
    denominator: "Average inventory",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "RI",
    ipoo: "output",
    gamingRisk: "Starving inventory to inflate turns.",
    gamingSeverity: "high",
    guardrail: "Stockout rate and OTIF as partner metrics.",
    dataSource: "ERP",
  }),
  C({
    key: "npo.cost",
    category: "nonprofit",
    name: "Programme cost per outcome",
    nameAr: "تكلفة البرنامج لكل نتيجة",
    definition: "Fully loaded programme cost divided by verified beneficiary outcomes, not activities.",
    purpose: "Stops celebrating spend or headcount as impact.",
    unit: "currency / outcome",
    direction: "lower",
    frequency: "quarterly",
    formula: "Programme cost / Verified outcomes",
    numerator: "Programme cost",
    denominator: "Verified outcomes",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quality",
    parmenterType: "KPI",
    ipoo: "outcome",
    gamingRisk: "Redefining ‘outcome’ to be easier, or excluding overhead.",
    gamingSeverity: "high",
    guardrail: "Outcome definition locked with the board; finance-owned cost.",
    dataSource: "Finance + programme M&E",
  }),
  C({
    key: "pm.cpi",
    category: "project_management",
    name: "Cost performance index (CPI)",
    nameAr: "مؤشر أداء التكلفة",
    definition: "Earned value / Actual cost. <1 means over spend for work done.",
    purpose: "Project health that percent-complete slides routinely hide.",
    unit: "ratio",
    direction: "higher",
    frequency: "weekly",
    formula: "EV / AC",
    numerator: "Earned value",
    denominator: "Actual cost",
    leadingLagging: "lagging",
    resultDriver: "result",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "KPI",
    ipoo: "output",
    gamingRisk: "Overstating earned value.",
    gamingSeverity: "high",
    guardrail: "Earned value rules frozen; independent PMO sample.",
    dataSource: "PMO tool",
  }),
  C({
    key: "pm.spi",
    category: "project_management",
    name: "Schedule performance index (SPI)",
    nameAr: "مؤشر أداء الجدول",
    definition: "Earned value / Planned value.",
    purpose: "Schedule truth.",
    unit: "ratio",
    direction: "higher",
    frequency: "weekly",
    formula: "EV / PV",
    numerator: "Earned value",
    denominator: "Planned value",
    leadingLagging: "leading",
    resultDriver: "driver",
    efficiencyEffectiveness: "efficiency",
    qualityQuantity: "quantity",
    parmenterType: "PI",
    ipoo: "process",
    gamingRisk: "Rebaselining silently.",
    gamingSeverity: "high",
    guardrail: "Baseline changes require a versioned change request.",
    dataSource: "PMO tool",
  }),
];

export function catalogByCategory(id: IndustryId | "all"): CatalogKpi[] {
  if (id === "all") return CATALOG;
  return CATALOG.filter((k) => k.category === id);
}

export function findCatalog(key: string): CatalogKpi | undefined {
  return CATALOG.find((k) => k.key === key);
}

export function matchCatalogByName(name: string): CatalogKpi | undefined {
  const key = name.trim().toLowerCase();
  if (!key) return undefined;
  const exact = CATALOG.find((c) => c.name.toLowerCase() === key);
  if (exact) return exact;
  if (key.length < 4) return undefined;
  return CATALOG.find((c) => {
    const n = c.name.toLowerCase();
    return n === key || n.startsWith(key) || key.startsWith(n);
  });
}

export const CATEGORY_OBJECTIVE: Record<IndustryId, { title: string; description: string }[]> = {
  retail: [
    { title: "Grow profitable, repeatable store demand", description: "Improve conversion and basket quality without buying volume through discounting." },
    { title: "Protect margin and inventory integrity", description: "Gross margin and shrink are guardrails, not afterthoughts." },
  ],
  sales: [
    { title: "Win the right work at the right margin", description: "Effectiveness over activity. Coverage that is honest." },
    { title: "Keep and expand existing revenue", description: "Retention is usually a better KPI than new logos alone." },
  ],
  marketing: [
    { title: "Create demand that sales will qualify", description: "Pipeline quality over cheap volume." },
    { title: "Acquire customers that pay back", description: "CAC is only useful beside contribution margin." },
  ],
  hr: [
    { title: "Retain the people we cannot afford to lose", description: "Regrettable attrition, not generic turnover." },
    { title: "Hire for productivity, not headcount", description: "Time-to-productivity and 90-day retention over offer volume." },
  ],
  finance: [
    { title: "Turn operations into cash predictably", description: "Cash conversion and forecast integrity." },
    { title: "Make planning honest", description: "A missed target with a good forecast is different from a surprise." },
  ],
  operations: [
    { title: "Keep the customer promise", description: "OTIF as the operational outcome." },
    { title: "Shorten the cycle without hiding work", description: "Cycle time as a driver, with quality intact." },
  ],
  customer_service: [
    { title: "Resolve issues the first time", description: "FCR over tickets closed." },
    { title: "Protect the experience with honest samples", description: "CSAT only when response rate is real." },
  ],
  manufacturing: [
    { title: "Make it right the first time", description: "First-pass yield and scrap as quality truth." },
    { title: "Run plants that are available, fast and safe", description: "OEE with its three factors, and safety as a hard guardrail." },
  ],
  supply_chain: [
    { title: "Inbound reliability", description: "Supplier OTIF as a leading operational promise." },
    { title: "Free cash without starving the line", description: "Turns paired with stockout / OTIF." },
  ],
  it: [
    { title: "Ship change safely", description: "Lead time with change-fail rate as the partner KPI." },
    { title: "Reduce toil that customers feel", description: "Reliability outcomes over utilisation theatre." },
  ],
  education: [
    { title: "Learners demonstrate the intended skill", description: "Mastery on an authenticated assessment, not attendance." },
    { title: "Complete without diluting the standard", description: "Completion is an RI beside mastery, never the KPI." },
  ],
  training: [
    { title: "Training that changes the work", description: "On-the-job application within 30 days." },
    { title: "Protect assessment integrity", description: "Do not let completion become the goal." },
  ],
  nonprofit: [
    { title: "Verified outcomes per programme cost", description: "Impact, not activity or spend." },
    { title: "Steward restricted funds with integrity", description: "Cost definitions owned by finance." },
  ],
  project_management: [
    { title: "Deliver to a versioned baseline", description: "CPI and SPI instead of percent-complete slides." },
    { title: "Make change control visible", description: "Silent rebaselines are a governance failure." },
  ],
};
